<a href="https://colab.research.google.com/github/GhazaleZe/Python-Exercises/blob/main/Xarray_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
from functools import partial, partialmethod
from numpy.random import default_rng
import numpy as np

In [2]:
potentialCusts = 200
purchaseProb = 0.2

rng = default_rng(seed = 111)
numSims = 100

# create data frame to store simulated demand
newsDF = pd.DataFrame({"simNum": range(1, numSims+1),  # sequence of 1 to 100
                   "demand": rng.binomial(n = potentialCusts,
                                          p = purchaseProb,
                                          size = numSims)})

## google SEARCH PHRASE: get element-wise minimum of two columns in pandas dataframe
newsDF["profit_q42"] = 3 * np.minimum(newsDF.demand,42) - 1 * 42
newsDF["lostSales_q42"] = np.maximum(0,newsDF.demand - 42)

# view first few 5 rows of newsDF
newsDF.iloc[:5,:]

simNum  demand  profit_q42  lostSales_q42
0       1      42          84              0
1       2      47          84              5
2       3      43          84              1
3       4      41          81              0
4       5      38          72              0

In [3]:
from numpy.random import default_rng
import numpy as np
import xarray as xr

rng = default_rng(seed = 111)  ## set random seed
demand = rng.binomial(n=200,p=0.2,size=100)   ## get demand values

## make data array
xr.DataArray(data = demand)

<xarray.DataArray (dim_0: 100)>
array([42, 47, 43, 41, 38, 40, 41, 45, 29, 29, 49, 44, 41, 46, 40, 39, 37,
       41, 37, 37, 38, 28, 28, 39, 48, 38, 47, 41, 43, 37, 40, 41, 35, 44,
       41, 35, 35, 39, 35, 47, 45, 35, 30, 48, 44, 38, 35, 40, 44, 41, 38,
       47, 42, 35, 36, 36, 44, 37, 42, 41, 40, 36, 36, 43, 43, 48, 27, 44,
       38, 37, 32, 48, 49, 29, 37, 44, 46, 42, 33, 36, 49, 33, 46, 35, 36,
       34, 45, 36, 41, 44, 35, 36, 38, 31, 50, 47, 43, 47, 31, 37])
Dimensions without coordinates: dim_0

In [4]:
xr.DataArray(data = demand,  dims= 'draw')

<xarray.DataArray (draw: 100)>
array([42, 47, 43, 41, 38, 40, 41, 45, 29, 29, 49, 44, 41, 46, 40, 39, 37,
       41, 37, 37, 38, 28, 28, 39, 48, 38, 47, 41, 43, 37, 40, 41, 35, 44,
       41, 35, 35, 39, 35, 47, 45, 35, 30, 48, 44, 38, 35, 40, 44, 41, 38,
       47, 42, 35, 36, 36, 44, 37, 42, 41, 40, 36, 36, 43, 43, 48, 27, 44,
       38, 37, 32, 48, 49, 29, 37, 44, 46, 42, 33, 36, 49, 33, 46, 35, 36,
       34, 45, 36, 41, 44, 35, 36, 38, 31, 50, 47, 43, 47, 31, 37])
Dimensions without coordinates: draw

In [5]:
xr.DataArray(data = demand, dims = 'draw',coords = {"draw": np.arange(100)+1}, name = "demand")

<xarray.DataArray 'demand' (draw: 100)>
array([42, 47, 43, 41, 38, 40, 41, 45, 29, 29, 49, 44, 41, 46, 40, 39, 37,
       41, 37, 37, 38, 28, 28, 39, 48, 38, 47, 41, 43, 37, 40, 41, 35, 44,
       41, 35, 35, 39, 35, 47, 45, 35, 30, 48, 44, 38, 35, 40, 44, 41, 38,
       47, 42, 35, 36, 36, 44, 37, 42, 41, 40, 36, 36, 43, 43, 48, 27, 44,
       38, 37, 32, 48, 49, 29, 37, 44, 46, 42, 33, 36, 49, 33, 46, 35, 36,
       34, 45, 36, 41, 44, 35, 36, 38, 31, 50, 47, 43, 47, 31, 37])
Coordinates:
  * draw     (draw) int64 1 2 3 4 5 6 7 8 9 10 ... 92 93 94 95 96 97 98 99 100

In [7]:
## explicit labeling of coordinates - must use name now to create dataset later
demandDA = xr.DataArray(data = demand, coords = {"draw": np.arange(100)+1}, name = "demand")
demandDA

<xarray.DataArray 'demand' (draw: 100)>
array([42, 47, 43, 41, 38, 40, 41, 45, 29, 29, 49, 44, 41, 46, 40, 39, 37,
       41, 37, 37, 38, 28, 28, 39, 48, 38, 47, 41, 43, 37, 40, 41, 35, 44,
       41, 35, 35, 39, 35, 47, 45, 35, 30, 48, 44, 38, 35, 40, 44, 41, 38,
       47, 42, 35, 36, 36, 44, 37, 42, 41, 40, 36, 36, 43, 43, 48, 27, 44,
       38, 37, 32, 48, 49, 29, 37, 44, 46, 42, 33, 36, 49, 33, 46, 35, 36,
       34, 45, 36, 41, 44, 35, 36, 38, 31, 50, 47, 43, 47, 31, 37])
Coordinates:
  * draw     (draw) int64 1 2 3 4 5 6 7 8 9 10 ... 92 93 94 95 96 97 98 99 100

In [6]:
## creating a DataArray of order quantities - must use name now to create dataset later
orderDA = xr.DataArray(data = np.arange(25,51),
                       coords = {"orderQtyIndex": np.arange(25,51)},
                       name = "orderQty")
orderDA

<xarray.DataArray 'orderQty' (orderQtyIndex: 26)>
array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50])
Coordinates:
  * orderQtyIndex  (orderQtyIndex) int64 25 26 27 28 29 30 ... 45 46 47 48 49 50

In [13]:
# create dataset by combining data arrays
newsvDS = xr.merge([demandDA,orderDA])
newsvDS

<xarray.Dataset>
Dimensions:        (draw: 100, orderQtyIndex: 26)
Coordinates:
  * draw           (draw) int64 1 2 3 4 5 6 7 8 9 ... 93 94 95 96 97 98 99 100
  * orderQtyIndex  (orderQtyIndex) int64 25 26 27 28 29 30 ... 45 46 47 48 49 50
Data variables:
    demand         (draw) int64 42 47 43 41 38 40 41 45 ... 31 50 47 43 47 31 37
    orderQty       (orderQtyIndex) int64 25 26 27 28 29 30 ... 45 46 47 48 49 50

In [14]:
newsvDS.to_dataframe().head(50)

demand  orderQty
draw orderQtyIndex                  
1    25                 42        25
     26                 42        26
     27                 42        27
     28                 42        28
     29                 42        29
     30                 42        30
     31                 42        31
     32                 42        32
     33                 42        33
     34                 42        34
     35                 42        35
     36                 42        36
     37                 42        37
     38                 42        38
     39                 42        39
     40                 42        40
     41                 42        41
     42                 42        42
     43                 42        43
     44                 42        44
     45                 42        45
     46                 42        46
     47                 42        47
     48                 42        48
     49                 42        49
     50                 42        50
2    25                 47        25
     26                 47        26
     27                 47        27
     28                 47        28
     29                 47        29
     30                 47        30
     31                 47        31
     32                 47        32
     33                 47        33
     34                 47        34
     35                 47        35
     36                 47        36
     37                 47        37
     38                 47        38
     39                 47        39
     40                 47        40
     41                 47        41
     42                 47        42
     43                 47        43
     44                 47        44
     45                 47        45
     46                 47        46
     47                 47        47
     48                 47        48

In [19]:
(
    newsvDS
    .assign(soldNewspapers = np.minimum(newsvDS.demand, newsvDS.orderQty))
    .assign(revenue = lambda DS: 3* DS.soldNewspapers)
)



<xarray.Dataset>
Dimensions:         (draw: 100, orderQtyIndex: 26)
Coordinates:
  * draw            (draw) int64 1 2 3 4 5 6 7 8 9 ... 93 94 95 96 97 98 99 100
  * orderQtyIndex   (orderQtyIndex) int64 25 26 27 28 29 30 ... 46 47 48 49 50
Data variables:
    demand          (draw) int64 42 47 43 41 38 40 41 ... 31 50 47 43 47 31 37
    orderQty        (orderQtyIndex) int64 25 26 27 28 29 30 ... 46 47 48 49 50
    soldNewspapers  (draw, orderQtyIndex) int64 25 26 27 28 29 ... 37 37 37 37
    revenue         (draw, orderQtyIndex) int64 75 78 81 84 ... 111 111 111 111

In [22]:
newsvDS = (newsvDS
            .assign(soldNewspapers = np.minimum(newsvDS.demand,newsvDS.orderQty))
            .assign(revenue = lambda DS: 3 * DS.soldNewspapers)
            .assign(expense = 1 * newsvDS.orderQty)
            .assign(profit = lambda DS: DS.revenue - DS.expense)
            .assign(lostSales = np.maximum(0, newsvDS.demand - newsvDS.orderQty))
)

(newsvDS
 .to_dataframe()  #dataframe for printing
 .sample(5, random_state = 111))  ## show five rows of DF

demand  orderQty  soldNewspapers  revenue  expense  \
draw orderQtyIndex                                                       
39   36                 35        36              35      105       36   
22   46                 28        46              28       84       46   
17   47                 37        47              37      111       47   
60   35                 41        35              35      105       35   
21   48                 38        48              38      114       48   

                    profit  lostSales  
draw orderQtyIndex                     
39   36                 69          0  
22   46                 38          0  
17   47                 64          0  
60   35                 70          6  
21   48                 66          0

We can do this insted of the other, when chains of operations are not required.

In [21]:
newsvDS["soldNewspapers"] = np.minimum(newsvDS.demand,newsvDS.orderQty)
newsvDS["expense"] = newsvDS.orderQty
newsvDS["revenue"] = 3 * newsvDS.soldNewspapers
newsvDS["profit"] = newsvDS.revenue - newsvDS.expense
newsvDS["lostSales"] = np.maximum(0, newsvDS.demand - newsvDS.orderQty)
newsvDS

<xarray.Dataset>
Dimensions:         (draw: 100, orderQtyIndex: 26)
Coordinates:
  * draw            (draw) int64 1 2 3 4 5 6 7 8 9 ... 93 94 95 96 97 98 99 100
  * orderQtyIndex   (orderQtyIndex) int64 25 26 27 28 29 30 ... 46 47 48 49 50
Data variables:
    demand          (draw) int64 42 47 43 41 38 40 41 ... 31 50 47 43 47 31 37
    orderQty        (orderQtyIndex) int64 25 26 27 28 29 30 ... 46 47 48 49 50
    soldNewspapers  (draw, orderQtyIndex) int64 25 26 27 28 29 ... 37 37 37 37
    revenue         (draw, orderQtyIndex) int64 75 78 81 84 ... 111 111 111 111
    expense         (orderQtyIndex) int64 25 26 27 28 29 30 ... 46 47 48 49 50
    profit          (draw, orderQtyIndex) int64 50 52 54 56 58 ... 64 63 62 61
    lostSales       (draw, orderQtyIndex) int64 17 16 15 14 13 12 ... 0 0 0 0 0

In [23]:
# select a particular value for a dimension
newsvDS.sel(orderQtyIndex = 36) # returns 1-d dataset

<xarray.Dataset>
Dimensions:         (draw: 100)
Coordinates:
  * draw            (draw) int64 1 2 3 4 5 6 7 8 9 ... 93 94 95 96 97 98 99 100
    orderQtyIndex   int64 36
Data variables:
    demand          (draw) int64 42 47 43 41 38 40 41 ... 31 50 47 43 47 31 37
    orderQty        int64 36
    soldNewspapers  (draw) int64 36 36 36 36 36 36 36 ... 31 36 36 36 36 31 36
    revenue         (draw) int64 108 108 108 108 108 108 ... 108 108 108 93 108
    expense         int64 36
    profit          (draw) int64 72 72 72 72 72 72 72 ... 57 72 72 72 72 57 72
    lostSales       (draw) int64 6 11 7 5 2 4 5 9 0 0 ... 0 0 2 0 14 11 7 11 0 1

In [24]:
# slicing returns all values inside the range (inclusive)
# as long as the index labels are monotonic increasing
newsvDS.sel(orderQtyIndex = slice(36,38))

<xarray.Dataset>
Dimensions:         (draw: 100, orderQtyIndex: 3)
Coordinates:
  * draw            (draw) int64 1 2 3 4 5 6 7 8 9 ... 93 94 95 96 97 98 99 100
  * orderQtyIndex   (orderQtyIndex) int64 36 37 38
Data variables:
    demand          (draw) int64 42 47 43 41 38 40 41 ... 31 50 47 43 47 31 37
    orderQty        (orderQtyIndex) int64 36 37 38
    soldNewspapers  (draw, orderQtyIndex) int64 36 37 38 36 37 ... 31 36 37 37
    revenue         (draw, orderQtyIndex) int64 108 111 114 108 ... 108 111 111
    expense         (orderQtyIndex) int64 36 37 38
    profit          (draw, orderQtyIndex) int64 72 74 76 72 74 ... 55 72 74 73
    lostSales       (draw, orderQtyIndex) int64 6 5 4 11 10 9 7 ... 0 0 0 1 0 0

In [25]:
newsvDS.where(newsvDS.lostSales>0)

<xarray.Dataset>
Dimensions:         (draw: 100, orderQtyIndex: 26)
Coordinates:
  * draw            (draw) int64 1 2 3 4 5 6 7 8 9 ... 93 94 95 96 97 98 99 100
  * orderQtyIndex   (orderQtyIndex) int64 25 26 27 28 29 30 ... 46 47 48 49 50
Data variables:
    demand          (draw, orderQtyIndex) float64 42.0 42.0 42.0 ... nan nan nan
    orderQty        (orderQtyIndex, draw) float64 25.0 25.0 25.0 ... nan nan nan
    soldNewspapers  (draw, orderQtyIndex) float64 25.0 26.0 27.0 ... nan nan nan
    revenue         (draw, orderQtyIndex) float64 75.0 78.0 81.0 ... nan nan nan
    expense         (orderQtyIndex, draw) float64 25.0 25.0 25.0 ... nan nan nan
    profit          (draw, orderQtyIndex) float64 50.0 52.0 54.0 ... nan nan nan
    lostSales       (draw, orderQtyIndex) float64 17.0 16.0 15.0 ... nan nan nan

In [27]:
(newsvDS.where(newsvDS.lostSales > 0, drop = True)
 .to_dataframe()  #convert to pandas dataframe for printing
 .dropna() # pandas method to remove NaN rows
 .sample(5, random_state = 111))

demand  orderQty  soldNewspapers  revenue  expense  \
draw orderQtyIndex                                                       
30   34               37.0      34.0            34.0    102.0     34.0   
98   27               47.0      27.0            27.0     81.0     27.0   
100  26               37.0      26.0            26.0     78.0     26.0   
83   30               46.0      30.0            30.0     90.0     30.0   
26   34               38.0      34.0            34.0    102.0     34.0   

                    profit  lostSales  
draw orderQtyIndex                     
30   34               68.0        3.0  
98   27               54.0       20.0  
100  26               52.0       11.0  
83   30               60.0       16.0  
26   34               68.0        4.0

In [28]:
newsvDS.drop_dims("orderQtyIndex")

<xarray.Dataset>
Dimensions:  (draw: 100)
Coordinates:
  * draw     (draw) int64 1 2 3 4 5 6 7 8 9 10 ... 92 93 94 95 96 97 98 99 100
Data variables:
    demand   (draw) int64 42 47 43 41 38 40 41 45 29 ... 38 31 50 47 43 47 31 37

In [29]:
newsvDS.drop_vars(["revenue","expense"])

<xarray.Dataset>
Dimensions:         (draw: 100, orderQtyIndex: 26)
Coordinates:
  * draw            (draw) int64 1 2 3 4 5 6 7 8 9 ... 93 94 95 96 97 98 99 100
  * orderQtyIndex   (orderQtyIndex) int64 25 26 27 28 29 30 ... 46 47 48 49 50
Data variables:
    demand          (draw) int64 42 47 43 41 38 40 41 ... 31 50 47 43 47 31 37
    orderQty        (orderQtyIndex) int64 25 26 27 28 29 30 ... 46 47 48 49 50
    soldNewspapers  (draw, orderQtyIndex) int64 25 26 27 28 29 ... 37 37 37 37
    profit          (draw, orderQtyIndex) int64 50 52 54 56 58 ... 64 63 62 61
    lostSales       (draw, orderQtyIndex) int64 17 16 15 14 13 12 ... 0 0 0 0 0

In [30]:
newsvDS.to_dataframe().sort_values("profit")

demand  orderQty  soldNewspapers  revenue  expense  \
draw orderQtyIndex                                                       
67   50                 27        50              27       81       50   
     49                 27        49              27       81       49   
     48                 27        48              27       81       48   
23   50                 28        50              28       84       50   
67   47                 27        47              27       81       47   
...                    ...       ...             ...      ...      ...   
73   49                 49        49              49      147       49   
81   49                 49        49              49      147       49   
95   49                 50        49              49      147       49   
11   49                 49        49              49      147       49   
95   50                 50        50              50      150       50   

                    profit  lostSales  
draw orderQtyIndex                     
67   50                 31          0  
     49                 32          0  
     48                 33          0  
23   50                 34          0  
67   47                 34          0  
...                    ...        ...  
73   49                 98          0  
81   49                 98          0  
95   49                 98          1  
11   49                 98          0  
95   50                100          0  

[2600 rows x 7 columns]

In [33]:
## collapse the 100 draws into 1 summary statistic
newsvDS.profit.mean(dim = "draw")

<xarray.DataArray 'profit' (orderQtyIndex: 26)>
array([50.  , 52.  , 54.  , 55.97, 57.88, 59.7 , 61.49, 63.22, 64.92,
       66.56, 68.17, 69.51, 70.61, 71.47, 72.12, 72.68, 73.09, 73.2 ,
       73.19, 73.03, 72.63, 72.14, 71.56, 70.8 , 69.92, 68.95])
Coordinates:
  * orderQtyIndex  (orderQtyIndex) int64 25 26 27 28 29 30 ... 45 46 47 48 49 50

In [34]:
## create mean summary stats
(
    newsvDS
    .assign(expProfit = newsvDS.profit.mean(dim="draw"))
    .assign(expLossSales = newsvDS.lostSales.mean(dim="draw"))
)

<xarray.Dataset>
Dimensions:         (draw: 100, orderQtyIndex: 26)
Coordinates:
  * draw            (draw) int64 1 2 3 4 5 6 7 8 9 ... 93 94 95 96 97 98 99 100
  * orderQtyIndex   (orderQtyIndex) int64 25 26 27 28 29 30 ... 46 47 48 49 50
Data variables:
    demand          (draw) int64 42 47 43 41 38 40 41 ... 31 50 47 43 47 31 37
    orderQty        (orderQtyIndex) int64 25 26 27 28 29 30 ... 46 47 48 49 50
    soldNewspapers  (draw, orderQtyIndex) int64 25 26 27 28 29 ... 37 37 37 37
    revenue         (draw, orderQtyIndex) int64 75 78 81 84 ... 111 111 111 111
    expense         (orderQtyIndex) int64 25 26 27 28 29 30 ... 46 47 48 49 50
    profit          (draw, orderQtyIndex) int64 50 52 54 56 58 ... 64 63 62 61
    lostSales       (draw, orderQtyIndex) int64 17 16 15 14 13 12 ... 0 0 0 0 0
    expProfit       (orderQtyIndex) float64 50.0 52.0 54.0 ... 70.8 69.92 68.95
    expLossSales    (orderQtyIndex) float64 14.65 13.65 12.65 ... 0.05 0.01 0.0

In [37]:
## find average profit by orderQty
## see documentation here: https://docs.xarray.dev/en/stable/generated/xarray.core.groupby.DatasetGroupBy.mean.html
(
    newsvDS
    .get("profit")
    .groupby("orderQtyIndex")
    .mean(...)
).to_dataframe()

profit
orderQtyIndex        
25              50.00
26              52.00
27              54.00
28              55.97
29              57.88
30              59.70
31              61.49
32              63.22
33              64.92
34              66.56
35              68.17
36              69.51
37              70.61
38              71.47
39              72.12
40              72.68
41              73.09
42              73.20
43              73.19
44              73.03
45              72.63
46              72.14
47              71.56
48              70.80
49              69.92
50              68.95